name: Update

env:
  CED_ENVIRONMENT: development
  CED_CLI_TOKEN: ${{secrets.CED_CLI_TOKEN}}
  CED_PROJECT_PATH: Formula

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: MerthinTechnologies/push-ced-source-action@dev
